add_lunch_combo pa_gee-userdebug
add_lunch_combo pa_geeb-userdebug
add_lunch_combo pa_geehrc-userdebug
add_lunch_combo pa_grouper-userdebug
add_lunch_combo pa_d802-userdebug
add_lunch_combo pa_hammerhead-userdebug
add_lunch_combo pa_lu6200-userdebug
add_lunch_combo pa_mako-userdebug
